dataset_dir = "data/input/data_pcap"

[logging.stderr]
enable = true
level = "INFO"

[logging.logfile]
enable = true
level = "TRACE"
serialize = true

[hardware.iwr1843]
hw_def_class = "mmwavecapture.capture.RadarDCA"  # It should be `module.class_name`
dca_eth_interface = "en10"
radar_config_port = "/dev/tty.usbmodemR20910491"
radar_data_port = "/dev/tty.usbmodemR20910494"
dca_ip = "192.168.33.180"
dca_config_port = 4096
host_ip = "192.168.33.30"
radar_config_filename = "configs/profile_2.cfg"
capture_frames = 100

[metadata]
date = "2025-04-12"
location = "EPFL Lab"
operator = "Your Name"
notes = "First test capture"
